export const BLOG_ITEMS_FETCH = 'BLOG_ITEMS_FETCH';
export const BLOG_ITEMS_FETCH_SUCCESS = 'BLOG_ITEMS_FETCH_SUCCESS';
export const BLOG_ITEM_FETCH = 'BLOG_ITEM_FETCH';
export const BLOG_ITEM_FETCH_SUCCESS = 'BLOG_ITEM_FETCH_SUCCESS';
export const BLOG_ITEM_TOOGLE_MARK = 'BLOG_ITEM_TOOGLE_MARK';
